### ISSUE TITLE
Huge memory usage

### ISSUE THREAD

**Issue by tvoikoteika228** [wizden/Searcher#30]
After switching from v1.0.25 (SourceForge version) to 1.0.43 (latest release from GitHub) experienced massive RAM usage (up to 20GB) and slow scanning speed (~1000 files in 5 min, while v1.0.25 scanned 280000 files in the same time).
*v1.0.25 also have memory usage problems

**Comment by wizden** [comment]
That is quite a huge version jump. Between these versions, some of the changes that may have an impact on search were made, such as:
- Search capabilities for additional file types (would have ignored or searched incorrectly for these before)
- Third party package upgrades - Hopefully these should make things better, but sometimes it may not
This may have an impact on the search speed and search results.

Things you could check on your side are:
- Are both versions searching using the exact criteria (file filters / excluded files or directories)? If not, then they need to be the same to compare.
- Are you able to add additional file filters on the newer version to narrow down which files or file types are taking longer?

If there are genuine issues in the newer version, then your checks above could help identify the problem and I can try to make improvements.

**Comment by wizden** [comment]
No response from OP in a while, so closing off the issue for now.
